backend:
  name: git-gateway
  branch: main # Branch CMS commits changes to

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
# publish_mode: editorial_workflow # Enable for Draft Mode feature

collections:

  ### ~~~ HOME PAGE ~~~ ###
  - name: "homePage" # Used in routes, e.g., /admin/collections/blog
    identifier_field: pagename # Field used for collection item title in UI
    editor:
        preview: false
    label: "Home Page" # Used in the UI
    delete: false
    folder: "/content/home" # The path to the folder where the documents are stored
    create: false # Disable users from creating new documents in this collection
    slug: "{{slug}}" # Filename template (used when targeting in index.js)
    fields: # The fields for each document
      - {label: "Banner: Main Title", name: "title", minimal: true, buttons: ['bold','italic','link'], editor_components: [], modes: ['rich_text'], widget: "markdown"}
      - {label: "Banner: Subtitle", name: "subtitle", minimal: true, buttons: ['bold','italic','link'], editor_components: [], modes: ['rich_text'], widget: "markdown"}
      - {label: "Banner: Background Image", name: "heroimage", choose_url: false, widget: "image"}
      - {label: "Introduction: Text", name: "introtext", minimal: true, buttons: ['bold','italic','link'], editor_components: [], modes: ['rich_text'], widget: "markdown"}
      - label: "Documents"
        name: "documentcustom"
        widget: "list"
        summary: '{{fields.listitem}} - {{fields.documentfile}}'
        fields:
          - {label: Document Text, name: listitem, widget: markdown, minimal: true, buttons: ['bold','italic','link'], editor_components: [], modes: ['rich_text'], default: "Input your text here"}
          - {label: Document, name: documentfile, widget: file, media_folder: ../public/documents}
      - {label: "*Important* (Do Not Edit)", name: "pagename", widget: "string"} # identifier_field

  ### ~~~ ABOUT PAGE ~~~ ###
  - name: "aboutPage" # Used in routes, e.g., /admin/collections/blog
    identifier_field: About Page Content
    editor:
        preview: false
    label: "About Page" # Used in the UI
    folder: "/content/about" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Page Title", name: "title", widget: "string"}
      - {label: "Sub Title", name: "subtitle", widget: "string"}
      - {label: "Featured Image", name: "blogimage", required: false, widget: "image"}