import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Friends of Church Creek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>
        <div className="hero px-10vw bg-hero-bg py-20 bg-cover bg-center text-white">
          <div className='pt-4'>
            <h1 className='text-7xl text-center'>Friends Of Churn Creek</h1>
            <h2 className='text-2xl text-center pt-4'>Friends of Churn Creek Protected Area Society is a non-profit organization formed in 2009 to help BC Parks achieve the conservation and cultural heritage vision for Churn Creek Protected Area (CCPA).</h2>
            <div className="btn text-center pt-7">
              <Link className='bg-slate-600 py-3 px-8 text-lg font-semibold' href="#about">Learn More</Link>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
